# Generated by Django 4.2.7 on 2023-11-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field',
            new_name='Fields',
        ),
    ]
