# Generated by Django 4.2.7 on 2023-11-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='twiiter_url',
            new_name='twitter_url',
        ),
    ]
