# Generated by Django 4.2.7 on 2023-11-06 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_twiiter_url_profile_twitter_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.fields')),
            ],
        ),
    ]
